### ISSUE TITLE
Feature request: easy way for users to submit issues

### ISSUE THREAD

**Issue by hexylena** [TAMU-CPT/lims-frontend#1]
Rationale:

- Users will encounter things they want to complain about
- Should reduce friction and let them feel like they were heard

Implementation (Frontend):

- We should add a button prominently on the top bar for submitting a bug
- On click should launch a modal window that allows them to fill out a free-text field and click "submit"
- The screen should show some confirmation of being submitted to LIMS.
  - With raven, we get back an event ID. `Raven.lastEventId()`. We could even show this to the user and say "Please ask about <id_number> if you wish to follow up with this specific issue"? Not sure how useful that would be.

Implementation (Backend):

- I thought about writing our own model because that would be easy, but then realised that there are public django apps for this
- Looking through a number, most weren't geared towards our decoupled  djangular situation
- What if, instead, we used Sentry for this. We allow them to fill out a comment section, then we intentionally trigger a message that goes to sentry. That will collect all of the required browser/url/metadata/javascripty things we might want to collect, and we can optionally push our own field there.
  - https://docs.sentry.io/clients/javascript/
  - We should start calling Raven.setUserContext whenever a user logs in
  - https://docs.sentry.io/clients/javascript/usage/#passing-additional-data looks promising / useful for just using as a "submit feedback" type API, especially the "extra" block for various portions of the bug report.

**Comment by elenimijalis** [comment]
added this feature in 249574d, but had to setusercontext again
