### ISSUE TITLE
add validation for injected storage forms

### ISSUE THREAD

**Issue by elenimijalis** [TAMU-CPT/lims-frontend#10]
I'm not sure on the best way to do this. You don't want to be able to submit a lysate without adding it's storage, so the button should disable until the proper storage info AND the proper lysate info is added. However, it's a bit complicated because we are (essentially) using nested forms when we ng-include the template code for storage_form.

**Comment by hexylena** [comment]
Ah, good point. (Did you mean to close this?)

I've been mostly ignoring the validation story up until now.

**Comment by elenimijalis** [comment]
Yes, I don't know which commit, but validation is mostly working for this now. I can't get ng messages to work for the nested form, but the boxes show up red if required and not filled out, and the button stays disabled. I called it good enough
