### ISSUE TITLE
map API isn't loading

### ISSUE THREAD

**Issue by elenimijalis** [TAMU-CPT/lims-frontend#14]
![screenshot from 2017-01-03 16-07-03](https://cloud.githubusercontent.com/assets/7033341/21624906/b58ec2c0-d1ce-11e6-9047-7bf281312680.png)

**Comment by elenimijalis** [comment]
this seems to be intermittent and only on environmental sample create

**Comment by hexylena** [comment]
Hahah yeah I have no idea, it happens to me mostly when I have the console open. Try closing the console, it should mostly go away.
