### ISSUE TITLE
Should lysate detail have an "add dnaprep" button?

### ISSUE THREAD

**Issue by elenimijalis** [TAMU-CPT/lims-frontend#18]
@erasche

**Comment by hexylena** [comment]
I don't think so, see https://github.com/TAMU-CPT/lims-frontend/issues/15#issuecomment-270945394 Counter opinions?

**Comment by elenimijalis** [comment]
I think we'd have to discuss what a user's central profile would be like. I'm not sure of the best way to lay things out so that it's intuitive for the user.
